services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
  admin:
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      - postgres
