import type { Metadata } from "next";
import "@/assets/style.css";

import { ThemeProvider, useTheme } from "next-themes";
import ThemeChanger from "../components/themeChanger";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en">
    //   <body
    //     className={`${geistSans.variable} ${geistMono.variable} antialiased`}
    //   >
    //     {children}
    //   </body>
    // </html>

    // {{!-- This is the default layout for all pages. Things like the header, footer,
    // and stylesheets are all contained in this file. --}}
    <html lang="en" suppressHydrationWarning>
      <head>
        <title>Caps Track</title>

        <meta charSet="utf-8"></meta>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        ></meta>

        <link
          rel="canonical"
          href="https://getbootstrap.com/docs/5.3/examples/starter-template/"
        ></link>

        <link rel="preconnect" href="https://fonts.googleapis.com"></link>
        <link rel="preconnect" href="https://fonts.gstatic.com"></link>
        {/* <meta name="theme-color" content="#712cf9" /> */}
        <link
          href="https://fonts.googleapis.com/css2?family=Bangers&family=Caveat:wght@400..700&family=Comic+Neue:ital,wght@0,300;0,400;0,700;1,300;1,400;1,700&family=Mea+Culpa&family=Nabla&family=Source+Code+Pro:ital,wght@0,200..900;1,200..900&display=swap"
          rel="stylesheet"
        ></link>

        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/@docsearch/css@3"
        ></link>
        {/* <!-- our style file, which is Bootstrap + our modifications. see scss/style.scss. --> */}
        <style>
          {`
                                .bd-placeholder-img {
                                  font - size: 1.125rem;
                                text-anchor: middle;
                                -webkit-user-select: none;
                                -moz-user-select: none;
                                user-select: none;
    }

                                @media (min-width: 768px) {
      .bd - placeholder - img - lg {
                                  font - size: 3.5rem;
      }
    }

                                .b-example-divider {
                                  width: 100%;
                                height: 3rem;
                                background-color: rgba(0, 0, 0, .1);
                                border: solid rgba(0, 0, 0, .15);
                                border-width: 1px 0;
                                box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
    }

                                .b-example-vr {
                                  flex - shrink: 0;
                                width: 1.5rem;
                                height: 100vh;
    }

                                .bi {
                                  vertical - align: -.125em;
                                fill: currentColor;
    }

                                .nav-scroller {
                                  position: relative;
                                z-index: 2;
                                height: 2.75rem;
                                overflow-y: hidden;
    }

                                .nav-scroller .nav {
                                  display: flex;
                                flex-wrap: nowrap;
                                padding-bottom: 1rem;
                                margin-top: -1px;
                                overflow-x: auto;
                                text-align: center;
                                white-space: nowrap;
                                -webkit-overflow-scrolling: touch;
    }

                                .btn-bd-primary {
                                  --bd - violet - bg: #712cf9;
                                --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

                                --bs-btn-font-weight: 600;
                                --bs-btn-color: var(--bs-white);
                                --bs-btn-bg: var(--bd-violet-bg);
                                --bs-btn-border-color: var(--bd-violet-bg);
                                --bs-btn-hover-color: var(--bs-white);
                                --bs-btn-hover-bg: #6528e0;
                                --bs-btn-hover-border-color: #6528e0;
                                --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
                                --bs-btn-active-color: var(--bs-btn-hover-color);
                                --bs-btn-active-bg: #5a23c8;
                                --bs-btn-active-border-color: #5a23c8;
    }

                                .bd-mode-toggle {
                                  z - index: 1500;
    }

                                .bd-mode-toggle .dropdown-menu .active .bi {
                                  display: block !important;
    }
`}
        </style>
      </head>

      <body>
        <ThemeProvider
          attribute="data-bs-theme"
          enableSystem={true}
          enableColorScheme={true}
        >
          {/* {{> helpModal}} */}

          <div className="container">
            <header className="d-flex flex-wrap justify-content-center py-3 mb-4 border-bottom">
              <a
                href="/"
                className="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none"
              >
                <svg className="bi me-2" width="40" height="32">
                  <use xlinkHref="#capstrack-logo"></use>
                </svg>
                <span className="fs-4">Caps Track</span>
              </a>

              <ul className="nav nav-pills">
                {/* {{!-- < li className="nav-item"><a href="#" className="nav-link active" aria-current="page">Home</a></li>
            <li className="nav-item"><a href="#" className="nav-link">Features</a></li>
            <li className="nav-item"><a href="#" className="nav-link">Pricing</a></li>
            <li className="nav-item"><a href="#" className="nav-link">FAQs</a></li> --}} */}
                <li className="nav-item">
                  <a href="live" className="nav-link">
                    📺
                  </a>
                </li>
              </ul>
            </header>
          </div>

          {children}

          <ThemeChanger />

          {/* <!-- button to toggle help modal --> */}
          <div className="dropdown position-fixed bottom-0 start-0 mb-3 ms-3 bd-mode-toggle">
            <button
              className="btn btn-bd-primary py-2 d-flex align-items-center"
              type="button"
              data-bs-toggle="modal"
              data-bs-target="#helpModal"
            >
              ?
            </button>
          </div>

          <svg width="82" height="82" xmlns="http://www.w3.org/2000/svg">
            <symbol id="capstrack-logo" viewBox="0 0 82 82">
              <g>
                <title>Caps Track</title>
                <text
                  fill="#000000"
                  stroke="#000"
                  strokeWidth="0"
                  x="7"
                  y="53.5"
                  id="svg_1"
                  fontSize="83"
                  fontFamily="'Caveat'"
                  textAnchor="start"
                  xmlSpace="preserve"
                >
                  c
                </text>
                <text
                  fill="#000000"
                  strokeWidth="0"
                  x="31"
                  y="66.5"
                  id="svg_2"
                  fontSize="83"
                  fontFamily="'Caveat'"
                  textAnchor="start"
                  xmlSpace="preserve"
                  transform="rotate(-3.44382 48.1395 39.25)"
                  stroke="#000"
                >
                  t
                </text>
              </g>
            </symbol>
          </svg>

          <div className="container">
            <footer className="pt-5 my-5 text-body-secondary py-3 border-top">
              {/* {{ #if phrase }}
            {{ phrase }}
            {{ else}}
            i'm never missing again
            {{/if}} */}
            </footer>
          </div>
          <script
            src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            crossOrigin="anonymous"
          ></script>
          <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
            integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
            crossOrigin="anonymous"
          ></script>
          <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossOrigin="anonymous"
          ></script>

          {/* <!-- popup help modal on first visit --> */}
          <script>
            {/* window.onload = function () {
            if (localStorage.getItem('hasvisited')) {
              return;
            }
          $('#helpModal').modal('show');
          localStorage.setItem('hasvisited', 'true');
          } */}
          </script>
        </ThemeProvider>
      </body>
    </html>
  );
}
