# Simple checks.
name: Checks

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install

      - name: Prettier check
        id: prettier
        run: |
          set +o errexit
          npx prettier --check .
          exit_code=$?
          echo "prettier_exit_code=$exit_code" >> $GITHUB_OUTPUT
          exit $exit_code
        continue-on-error: true

      - name: Typescript check
        id: typescript
        run: |
          set +o errexit
          npx tsc --noEmit
          exit_code=$?
          echo "typescript_exit_code=$exit_code" >> $GITHUB_OUTPUT
          exit $exit_code
        continue-on-error: true

      - name: ESLint check
        id: eslint
        run: |
          set +o errexit
          npx eslint .
          exit_code=$?
          echo "eslint_exit_code=$exit_code" >> $GITHUB_OUTPUT
          exit $exit_code
        continue-on-error: true

      - name: Check results
        # Error if any of the checks failed
        run: |
          # Turn on usual error handling, pipefail, etc
          set -o pipefail
          set -o nounset
          set -o errexit
          set -o errtrace

          exit_code=0

          if [ "${{ steps.prettier.outputs.prettier_exit_code }}" -ne 0 ]; then
            echo "Prettier check failed"
            exit_code=1
          fi
          if [ "${{ steps.typescript.outputs.typescript_exit_code }}" -ne 0 ]; then
            echo "Typescript check failed"
            exit_code=1
          fi
          if [ "${{ steps.eslint.outputs.eslint_exit_code }}" -ne 0 ]; then
            echo "ESLint check failed"
            exit_code=1
          fi
          if [ $exit_code -ne 0 ]; then
            echo "One or more checks failed"
          fi

          exit $exit_code
