# Simple checks.
name: Checks

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install

      - name: Prettier check
        id: prettier
        run: |
          npx prettier --check .
          echo "prettier_exit_code=$?" >> $GITHUB_OUTPUT
        continue-on-error: true
      
      - name: Typescript check
        id: typescript
        run: |
          npx tsc --noEmit
          echo "typescript_exit_code=$?" >> $GITHUB_OUTPUT
        continue-on-error: true
      
      - name: ESLint check
        id: eslint
        run: |
          npx eslint .
          echo "eslint_exit_code=$?" >> $GITHUB_OUTPUT
        continue-on-error: true

      - name: Check results 
        # Error if any of the checks failed
        run: |
          exit_code=0

          if [ "${{ steps.prettier.outputs.prettier_exit_code }}" -ne 0 ]; then
            echo "Prettier check failed"
            exit_code=1
          fi
          if [ "${{ steps.typescript.outputs.typescript_exit_code }}" -ne 0 ]; then
            echo "Typescript check failed"
            exit_code=1
          fi
          if [ "${{ steps.eslint.outputs.eslint_exit_code }}" -ne 0 ]; then
            echo "ESLint check failed"
            exit_code=1
          fi
          if [ $exit_code -ne 0 ]; then
            echo "One or more checks failed"
          fi

          exit $exit_code