name: Checks

on: 
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Prettier Action
        uses: creyD/prettier_action@v4.6
        with:
          prettier_options: --check
          dry: true
          no_commit: true
